USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS AGENT_COMMERCE;

CREATE WAREHOUSE IF NOT EXISTS AGENT_COMMERCE_WH
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 120
    AUTO_RESUME = TRUE;

CREATE ROLE IF NOT EXISTS AGENT_COMMERCE_ROLE;

GRANT USAGE ON WAREHOUSE AGENT_COMMERCE_WH TO ROLE AGENT_COMMERCE_ROLE;
GRANT ALL ON DATABASE AGENT_COMMERCE TO ROLE AGENT_COMMERCE_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE AGENT_COMMERCE_ROLE;

USE ROLE AGENT_COMMERCE_ROLE;
USE DATABASE AGENT_COMMERCE;
USE WAREHOUSE AGENT_COMMERCE_WH;

CREATE SCHEMA IF NOT EXISTS PRODUCTS COMMENT='Product catalog and pricing';
CREATE SCHEMA IF NOT EXISTS SOCIAL COMMENT='Reviews and social proof';
CREATE SCHEMA IF NOT EXISTS INVENTORY COMMENT='Stock levels and locations';
CREATE SCHEMA IF NOT EXISTS CUSTOMERS COMMENT='Customer profiles and face embeddings';
CREATE SCHEMA IF NOT EXISTS CART_OLTP COMMENT='Transactional cart and orders (Hybrid Tables)';
CREATE SCHEMA IF NOT EXISTS UTIL COMMENT='Utilities, configs, and shared resources';

USE SCHEMA UTIL;

CREATE OR REPLACE TAG PII ALLOWED_VALUES 'TRUE', 'FALSE' COMMENT='Indicates if column contains personally identifiable information';
CREATE OR REPLACE TAG PCI ALLOWED_VALUES 'TRUE', 'FALSE' COMMENT='Indicates if column contains payment card industry data';

CREATE OR REPLACE FILE FORMAT CSV_FORMAT
    PARSE_HEADER = TRUE
    FIELD_OPTIONALLY_ENCLOSED_BY = '"'
    NULL_IF = ('', 'NULL', 'null')
    ERROR_ON_COLUMN_COUNT_MISMATCH = FALSE;

CREATE API INTEGRATION IF NOT EXISTS AGENT_COMMERCE_GIT_INTEGRATION
    API_PROVIDER = GIT_HTTPS_API
    API_ALLOWED_PREFIXES = ('https://github.com/sfc-gh-amgupta')
    ENABLED = TRUE;

CREATE GIT REPOSITORY IF NOT EXISTS AGENT_COMMERCE.UTIL.AGENT_COMMERCE_GIT
    API_INTEGRATION = AGENT_COMMERCE_GIT_INTEGRATION
    ORIGIN = 'https://github.com/sfc-gh-amgupta/agent_commerce_beauty_advisor_v2.git';

CREATE STAGE IF NOT EXISTS UTIL.CSV_DATA_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE');

CREATE STAGE IF NOT EXISTS PRODUCTS.PRODUCT_LABELS_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Product label images for AI extraction';

CREATE STAGE IF NOT EXISTS PRODUCTS.PRODUCT_MEDIA_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Product media assets (swatch images, label photos)';

CREATE STAGE IF NOT EXISTS CUSTOMERS.FACE_IMAGES_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE)
    COMMENT = 'Customer face images for embedding extraction';

CREATE STAGE IF NOT EXISTS CUSTOMERS.FACE_UPLOAD_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE);

CREATE STAGE IF NOT EXISTS UTIL.EXECUTIVE_360_STAGE
    ENCRYPTION = (TYPE = 'SNOWFLAKE_SSE')
    DIRECTORY = (ENABLE = TRUE);

CREATE NOTIFICATION INTEGRATION IF NOT EXISTS EMAIL_INTEGRATION
    TYPE = EMAIL
    ALLOWED_RECIPIENTS = ('cdo@operations.com', 'coo@operations.com')
    ENABLED = TRUE;

-- External access integration for SPCS backend
-- Update the FQDN after SPCS service is created
CREATE OR REPLACE NETWORK RULE SPCS_BACKEND_RULE
    MODE = EGRESS
    TYPE = HOST_PORT
    VALUE_LIST = ('placeholder-spcs-service.snowflakecomputing.app');

CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION SPCS_BACKEND_ACCESS
    ALLOWED_NETWORK_RULES = (SPCS_BACKEND_RULE)
    ENABLED = TRUE;

CREATE COMPUTE POOL IF NOT EXISTS AGENT_COMMERCE_POOL
    MIN_NODES = 1
    MAX_NODES = 1
    INSTANCE_FAMILY = CPU_X64_S
    AUTO_RESUME = TRUE
    AUTO_SUSPEND_SECS = 300;
