USE ROLE AGENT_COMMERCE_ROLE;
USE DATABASE AGENT_COMMERCE;
USE WAREHOUSE AGENT_COMMERCE_WH;

-- ============================================================
-- PRODUCTS schema
-- ============================================================
USE SCHEMA PRODUCTS;

CREATE OR REPLACE TABLE PRODUCTS (
    PRODUCT_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    SKU VARCHAR(50),
    NAME VARCHAR(255) NOT NULL,
    BRAND VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    SUBCATEGORY VARCHAR(50),
    DESCRIPTION VARCHAR(16777216),
    SHORT_DESCRIPTION VARCHAR(500),
    BASE_PRICE NUMBER(10,2) NOT NULL,
    CURRENT_PRICE NUMBER(10,2) NOT NULL,
    COST NUMBER(10,2),
    COLOR_HEX VARCHAR(7),
    COLOR_LAB ARRAY,
    COLOR_NAME VARCHAR(50),
    FINISH VARCHAR(30),
    SKIN_TONE_COMPATIBILITY ARRAY,
    UNDERTONE_COMPATIBILITY ARRAY,
    MONK_SCALE_MIN NUMBER(38,0),
    MONK_SCALE_MAX NUMBER(38,0),
    SIZE VARCHAR(50),
    SIZE_UNIT VARCHAR(20),
    INGREDIENTS VARCHAR(16777216),
    IS_VEGAN BOOLEAN DEFAULT FALSE,
    IS_CRUELTY_FREE BOOLEAN DEFAULT FALSE,
    SPF_VALUE NUMBER(38,0),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IS_FEATURED BOOLEAN DEFAULT FALSE,
    LAUNCH_DATE DATE,
    DISCONTINUE_DATE DATE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9),
    SKIN_TYPE_COMPATIBILITY ARRAY,
    UNIQUE (SKU),
    PRIMARY KEY (PRODUCT_ID)
);

CREATE OR REPLACE TABLE PRODUCT_VARIANTS (
    VARIANT_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    SKU VARCHAR(50),
    SHADE_NAME VARCHAR(100),
    SHADE_CODE VARCHAR(20),
    COLOR_HEX VARCHAR(7),
    COLOR_LAB ARRAY,
    SIZE VARCHAR(50),
    SIZE_UNIT VARCHAR(20),
    PRICE_MODIFIER NUMBER(10,2) DEFAULT 0,
    IS_AVAILABLE BOOLEAN DEFAULT TRUE,
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    DISPLAY_ORDER NUMBER(38,0) DEFAULT 0,
    UNIQUE (SKU),
    PRIMARY KEY (VARIANT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS.PRODUCTS(PRODUCT_ID)
);

CREATE OR REPLACE TABLE PRODUCT_MEDIA (
    MEDIA_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    VARIANT_ID VARCHAR(36),
    URL VARCHAR(1000) NOT NULL,
    MEDIA_TYPE VARCHAR(20) NOT NULL,
    MEDIA_SUBTYPE VARCHAR(30),
    ALT_TEXT VARCHAR(255),
    WIDTH NUMBER(38,0),
    HEIGHT NUMBER(38,0),
    FILE_SIZE_BYTES NUMBER(38,0),
    DISPLAY_ORDER NUMBER(38,0) DEFAULT 0,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    IS_PROCESSED BOOLEAN DEFAULT FALSE,
    PROCESSED_AT TIMESTAMP_NTZ(9),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MEDIA_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS.PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (VARIANT_ID) REFERENCES PRODUCTS.PRODUCT_VARIANTS(VARIANT_ID)
);

CREATE OR REPLACE TABLE PRODUCT_LABELS (
    LABEL_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    LABEL_TYPE VARCHAR(30) NOT NULL,
    EXTRACTED_TEXT VARCHAR(16777216),
    STRUCTURED_DATA VARIANT,
    SOURCE_IMAGE_URL VARCHAR(1000),
    SOURCE_MEDIA_ID VARCHAR(36),
    EXTRACTION_MODEL VARCHAR(50),
    EXTRACTION_CONFIDENCE FLOAT,
    EXTRACTION_DATE TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (LABEL_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS.PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (SOURCE_MEDIA_ID) REFERENCES PRODUCTS.PRODUCT_MEDIA(MEDIA_ID)
);

CREATE OR REPLACE TABLE PRODUCT_INGREDIENTS (
    INGREDIENT_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    LABEL_ID VARCHAR(36),
    INGREDIENT_NAME VARCHAR(255) NOT NULL,
    INGREDIENT_NAME_NORMALIZED VARCHAR(255),
    POSITION NUMBER(38,0),
    PERCENTAGE FLOAT,
    IS_ACTIVE BOOLEAN DEFAULT FALSE,
    IS_ALLERGEN BOOLEAN DEFAULT FALSE,
    ALLERGEN_TYPE VARCHAR(50),
    SOURCE_IMAGE_URL VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (INGREDIENT_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS.PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (LABEL_ID) REFERENCES PRODUCTS.PRODUCT_LABELS(LABEL_ID)
);

CREATE OR REPLACE TABLE PRODUCT_WARNINGS (
    WARNING_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    LABEL_ID VARCHAR(36),
    WARNING_TYPE VARCHAR(50),
    WARNING_TEXT VARCHAR(16777216) NOT NULL,
    SEVERITY VARCHAR(20),
    SOURCE_IMAGE_URL VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (WARNING_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS.PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (LABEL_ID) REFERENCES PRODUCTS.PRODUCT_LABELS(LABEL_ID)
);

CREATE OR REPLACE TABLE PRODUCT_LABEL_FILES (
    FILE_PATH VARCHAR(16777216)
);

CREATE OR REPLACE TABLE PRICE_HISTORY (
    HISTORY_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    VARIANT_ID VARCHAR(36),
    PRICE NUMBER(10,2) NOT NULL,
    PREVIOUS_PRICE NUMBER(10,2),
    EFFECTIVE_DATE DATE NOT NULL,
    END_DATE DATE,
    CHANGE_REASON VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (HISTORY_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS.PRODUCTS(PRODUCT_ID),
    FOREIGN KEY (VARIANT_ID) REFERENCES PRODUCTS.PRODUCT_VARIANTS(VARIANT_ID)
);

CREATE OR REPLACE TABLE PROMOTIONS (
    PROMOTION_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(16777216),
    PROMO_CODE VARCHAR(50),
    DISCOUNT_TYPE VARCHAR(20) NOT NULL,
    DISCOUNT_VALUE NUMBER(10,2),
    APPLIES_TO VARCHAR(20),
    PRODUCT_IDS ARRAY,
    CATEGORY_IDS ARRAY,
    BRAND_NAMES ARRAY,
    MIN_PURCHASE_AMOUNT NUMBER(10,2),
    MAX_USES NUMBER(38,0),
    MAX_USES_PER_CUSTOMER NUMBER(38,0),
    CURRENT_USES NUMBER(38,0) DEFAULT 0,
    START_DATE TIMESTAMP_NTZ(9) NOT NULL,
    END_DATE TIMESTAMP_NTZ(9) NOT NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (PROMOTION_ID)
);

CREATE OR REPLACE TABLE LABEL_EXTRACTIONS_STAGING (
    EXTRACTION_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    FILE_PATH VARCHAR(500),
    SKU VARCHAR(20),
    EXTRACTED_DATA VARIANT,
    EXTRACTION_TIMESTAMP TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (EXTRACTION_ID)
);

-- ============================================================
-- SOCIAL schema
-- ============================================================
USE SCHEMA SOCIAL;

CREATE OR REPLACE TABLE PRODUCT_REVIEWS (
    REVIEW_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    CUSTOMER_ID VARCHAR(36),
    PLATFORM VARCHAR(30) NOT NULL,
    RATING NUMBER(38,0) NOT NULL,
    TITLE VARCHAR(255),
    REVIEW_TEXT VARCHAR(16777216),
    REVIEW_URL VARCHAR(1000),
    HELPFUL_VOTES NUMBER(38,0) DEFAULT 0,
    NOT_HELPFUL_VOTES NUMBER(38,0) DEFAULT 0,
    VERIFIED_PURCHASE BOOLEAN DEFAULT FALSE,
    REVIEWER_SKIN_TONE VARCHAR(30),
    REVIEWER_SKIN_TYPE VARCHAR(30),
    REVIEWER_UNDERTONE VARCHAR(20),
    REVIEWER_AGE_RANGE VARCHAR(20),
    IS_APPROVED BOOLEAN DEFAULT TRUE,
    MODERATION_STATUS VARCHAR(20),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9),
    PRIMARY KEY (REVIEW_ID)
);

CREATE OR REPLACE TABLE SOCIAL_MENTIONS (
    MENTION_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    PLATFORM VARCHAR(30) NOT NULL,
    POST_URL VARCHAR(1000) NOT NULL,
    CONTENT_TEXT VARCHAR(16777216),
    MEDIA_URL VARCHAR(1000),
    AUTHOR_HANDLE VARCHAR(100),
    AUTHOR_NAME VARCHAR(255),
    AUTHOR_FOLLOWER_COUNT NUMBER(38,0),
    LIKES NUMBER(38,0) DEFAULT 0,
    COMMENTS NUMBER(38,0) DEFAULT 0,
    SHARES NUMBER(38,0) DEFAULT 0,
    VIEWS NUMBER(38,0) DEFAULT 0,
    SENTIMENT_SCORE FLOAT,
    SENTIMENT_LABEL VARCHAR(20),
    POSTED_AT TIMESTAMP_NTZ(9),
    INGESTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MENTION_ID)
);

CREATE OR REPLACE TABLE INFLUENCER_MENTIONS (
    MENTION_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    INFLUENCER_ID VARCHAR(36),
    INFLUENCER_HANDLE VARCHAR(100) NOT NULL,
    INFLUENCER_NAME VARCHAR(255),
    PLATFORM VARCHAR(30) NOT NULL,
    POST_URL VARCHAR(1000) NOT NULL,
    CONTENT_TEXT VARCHAR(16777216),
    MEDIA_URL VARCHAR(1000),
    CONTENT_TYPE VARCHAR(30),
    LIKES NUMBER(38,0) DEFAULT 0,
    COMMENTS NUMBER(38,0) DEFAULT 0,
    SHARES NUMBER(38,0) DEFAULT 0,
    VIEWS NUMBER(38,0) DEFAULT 0,
    INFLUENCER_SKIN_TONE VARCHAR(30),
    INFLUENCER_SKIN_TYPE VARCHAR(30),
    INFLUENCER_UNDERTONE VARCHAR(20),
    FOLLOWER_COUNT NUMBER(38,0),
    ENGAGEMENT_RATE FLOAT,
    AUDIENCE_DEMOGRAPHICS OBJECT,
    IS_SPONSORED BOOLEAN DEFAULT FALSE,
    IS_AFFILIATE BOOLEAN DEFAULT FALSE,
    POSTED_AT TIMESTAMP_NTZ(9),
    INGESTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (MENTION_ID)
);

CREATE OR REPLACE TABLE TRENDING_PRODUCTS (
    TREND_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    TREND_RANK NUMBER(38,0),
    TREND_SCORE FLOAT,
    MENTION_VELOCITY FLOAT,
    SENTIMENT_AVERAGE FLOAT,
    IS_VIRAL BOOLEAN DEFAULT FALSE,
    VIRAL_REASON VARCHAR(255),
    TRENDING_PLATFORMS ARRAY,
    TOP_HASHTAGS ARRAY,
    WINDOW_START TIMESTAMP_NTZ(9),
    WINDOW_END TIMESTAMP_NTZ(9),
    CALCULATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (TREND_ID)
);

-- ============================================================
-- INVENTORY schema
-- ============================================================
USE SCHEMA INVENTORY;

CREATE OR REPLACE TABLE LOCATIONS (
    LOCATION_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    NAME VARCHAR(255) NOT NULL,
    LOCATION_TYPE VARCHAR(20) NOT NULL,
    LOCATION_CODE VARCHAR(20),
    ADDRESS_LINE1 VARCHAR(255),
    ADDRESS_LINE2 VARCHAR(255),
    CITY VARCHAR(100),
    STATE VARCHAR(50),
    POSTAL_CODE VARCHAR(20),
    COUNTRY VARCHAR(2) DEFAULT 'US',
    LATITUDE FLOAT,
    LONGITUDE FLOAT,
    PHONE VARCHAR(20),
    EMAIL VARCHAR(255),
    OPERATING_HOURS OBJECT,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IS_PICKUP_ENABLED BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (LOCATION_CODE),
    PRIMARY KEY (LOCATION_ID)
);

CREATE OR REPLACE TABLE STOCK_LEVELS (
    STOCK_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    PRODUCT_ID VARCHAR(36) NOT NULL,
    VARIANT_ID VARCHAR(36),
    LOCATION_ID VARCHAR(36) NOT NULL,
    QUANTITY_ON_HAND NUMBER(38,0) NOT NULL DEFAULT 0,
    QUANTITY_RESERVED NUMBER(38,0) NOT NULL DEFAULT 0,
    REORDER_POINT NUMBER(38,0) DEFAULT 10,
    REORDER_QUANTITY NUMBER(38,0) DEFAULT 50,
    LAST_RESTOCK_DATE DATE,
    LAST_UPDATED TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UNIQUE (PRODUCT_ID, VARIANT_ID, LOCATION_ID),
    PRIMARY KEY (STOCK_ID),
    FOREIGN KEY (LOCATION_ID) REFERENCES INVENTORY.LOCATIONS(LOCATION_ID)
);

CREATE OR REPLACE TABLE INVENTORY_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    STOCK_ID VARCHAR(36) NOT NULL,
    TRANSACTION_TYPE VARCHAR(30) NOT NULL,
    QUANTITY NUMBER(38,0) NOT NULL,
    QUANTITY_BEFORE NUMBER(38,0),
    QUANTITY_AFTER NUMBER(38,0),
    REFERENCE_TYPE VARCHAR(30),
    REFERENCE_ID VARCHAR(36),
    NOTES VARCHAR(16777216),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CREATED_BY VARCHAR(100),
    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (STOCK_ID) REFERENCES INVENTORY.STOCK_LEVELS(STOCK_ID)
);

-- ============================================================
-- CUSTOMERS schema
-- ============================================================
USE SCHEMA CUSTOMERS;

CREATE OR REPLACE TABLE CUSTOMERS (
    CUSTOMER_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    EMAIL VARCHAR(255),
    FIRST_NAME VARCHAR(100),
    LAST_NAME VARCHAR(100),
    PHONE VARCHAR(20),
    LOYALTY_TIER VARCHAR(20) DEFAULT 'Bronze',
    POINTS_BALANCE NUMBER(38,0) DEFAULT 0,
    LIFETIME_POINTS NUMBER(38,0) DEFAULT 0,
    SKIN_PROFILE OBJECT,
    PREFERENCES OBJECT,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9),
    LAST_LOGIN_AT TIMESTAMP_NTZ(9),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    UNIQUE (EMAIL),
    PRIMARY KEY (CUSTOMER_ID)
);

CREATE OR REPLACE TABLE CUSTOMER_FACE_EMBEDDINGS (
    EMBEDDING_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    CUSTOMER_ID VARCHAR(36) NOT NULL,
    EMBEDDING VECTOR(FLOAT, 128) NOT NULL,
    QUALITY_SCORE FLOAT,
    LIGHTING_CONDITION VARCHAR(20),
    FACE_ANGLE VARCHAR(20),
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    IS_PRIMARY BOOLEAN DEFAULT FALSE,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    SOURCE VARCHAR(50),
    PRIMARY KEY (EMBEDDING_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS.CUSTOMERS(CUSTOMER_ID)
);

CREATE OR REPLACE TABLE FACE_IMAGE_PROCESSING (
    PROCESSING_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    FILE_NAME VARCHAR(255),
    FILE_PATH VARCHAR(500),
    CUSTOMER_ID VARCHAR(36),
    PROCESSED BOOLEAN DEFAULT FALSE,
    EMBEDDING ARRAY,
    QUALITY_SCORE FLOAT,
    ERROR_MESSAGE VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PROCESSED_AT TIMESTAMP_NTZ(9),
    PRIMARY KEY (PROCESSING_ID)
);

CREATE OR REPLACE TABLE SKIN_ANALYSIS_HISTORY (
    ANALYSIS_ID VARCHAR(36) NOT NULL DEFAULT UUID_STRING(),
    CUSTOMER_ID VARCHAR(36),
    IMAGE_STAGE_PATH VARCHAR(500),
    SKIN_HEX VARCHAR(7),
    SKIN_LAB ARRAY,
    SKIN_RGB ARRAY,
    LIP_HEX VARCHAR(7),
    LIP_LAB ARRAY,
    LIP_RGB ARRAY,
    LIP_IS_NATURAL BOOLEAN,
    ESTIMATED_NATURAL_LIP_HEX VARCHAR(7),
    FITZPATRICK_TYPE NUMBER(38,0),
    MONK_SHADE NUMBER(38,0),
    UNDERTONE VARCHAR(20),
    ITA_ANGLE FLOAT,
    MAKEUP_DETECTED BOOLEAN DEFAULT FALSE,
    DETECTED_MAKEUP_TYPES ARRAY,
    CONFIDENCE_SCORE FLOAT,
    FACE_QUALITY_SCORE FLOAT,
    LIGHTING_QUALITY VARCHAR(20),
    ANALYZED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    ANALYSIS_DURATION_MS NUMBER(38,0),
    MODEL_VERSION VARCHAR(20),
    PRIMARY KEY (ANALYSIS_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS.CUSTOMERS(CUSTOMER_ID)
);

-- ============================================================
-- CART_OLTP schema (Hybrid Tables)
-- ============================================================
USE SCHEMA CART_OLTP;

CREATE OR REPLACE HYBRID TABLE CART_SESSIONS (
    SESSION_ID VARCHAR(36) NOT NULL,
    CUSTOMER_ID VARCHAR(36),
    STATUS VARCHAR(30) NOT NULL DEFAULT 'active',
    SUBTOTAL_CENTS NUMBER(38,0) DEFAULT 0,
    TAX_CENTS NUMBER(38,0) DEFAULT 0,
    SHIPPING_CENTS NUMBER(38,0) DEFAULT 0,
    DISCOUNT_CENTS NUMBER(38,0) DEFAULT 0,
    TOTAL_CENTS NUMBER(38,0) DEFAULT 0,
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    APPLIED_PROMO_CODES VARCHAR(1000),
    APPLIED_LOYALTY_POINTS NUMBER(38,0) DEFAULT 0,
    FULFILLMENT_TYPE VARCHAR(20),
    SHIPPING_ADDRESS VARCHAR(2000),
    BILLING_ADDRESS VARCHAR(2000),
    SHIPPING_METHOD_ID VARCHAR(36),
    IS_GIFT BOOLEAN DEFAULT FALSE,
    GIFT_MESSAGE VARCHAR(500),
    GIFT_RECIPIENT_EMAIL VARCHAR(255),
    IS_VALID BOOLEAN DEFAULT TRUE,
    VALIDATION_MESSAGE VARCHAR(500),
    IDEMPOTENCY_KEY VARCHAR(100),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9),
    EXPIRES_AT TIMESTAMP_NTZ(9),
    COMPLETED_AT TIMESTAMP_NTZ(9),
    PRIMARY KEY (SESSION_ID),
    INDEX IDX_CART_CUSTOMER(CUSTOMER_ID),
    INDEX IDX_CART_STATUS(STATUS)
);

CREATE OR REPLACE HYBRID TABLE FULFILLMENT_OPTIONS (
    OPTION_ID VARCHAR(36) NOT NULL,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(255),
    FULFILLMENT_TYPE VARCHAR(20) NOT NULL,
    PRICE_CENTS NUMBER(38,0) NOT NULL,
    FREE_THRESHOLD_CENTS NUMBER(38,0),
    ESTIMATED_DAYS_MIN NUMBER(38,0),
    ESTIMATED_DAYS_MAX NUMBER(38,0),
    CARRIER VARCHAR(50),
    IS_AVAILABLE BOOLEAN DEFAULT TRUE,
    AVAILABLE_COUNTRIES VARCHAR(500),
    DISPLAY_ORDER NUMBER(38,0) DEFAULT 0,
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (OPTION_ID),
    INDEX IDX_FULFILLMENT_AVAILABLE(IS_AVAILABLE, FULFILLMENT_TYPE)
);

CREATE OR REPLACE HYBRID TABLE PAYMENT_METHODS (
    PAYMENT_METHOD_ID VARCHAR(36) NOT NULL,
    CUSTOMER_ID VARCHAR(36) NOT NULL,
    PAYMENT_TYPE VARCHAR(30) NOT NULL,
    TOKEN VARCHAR(255) NOT NULL,
    DISPLAY_NAME VARCHAR(100),
    CARD_BRAND VARCHAR(20),
    CARD_LAST_FOUR VARCHAR(4),
    EXPIRES_MONTH NUMBER(38,0),
    EXPIRES_YEAR NUMBER(38,0),
    IS_DEFAULT BOOLEAN DEFAULT FALSE,
    IS_VERIFIED BOOLEAN DEFAULT FALSE,
    BILLING_ADDRESS VARCHAR(2000),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    LAST_USED_AT TIMESTAMP_NTZ(9),
    PRIMARY KEY (PAYMENT_METHOD_ID),
    INDEX IDX_PAYMENT_CUSTOMER(CUSTOMER_ID)
);

CREATE OR REPLACE HYBRID TABLE CART_ITEMS (
    ITEM_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36) NOT NULL,
    PRODUCT_ID VARCHAR(36) NOT NULL,
    VARIANT_ID VARCHAR(36),
    QUANTITY NUMBER(38,0) NOT NULL DEFAULT 1,
    UNIT_PRICE_CENTS NUMBER(38,0) NOT NULL,
    SUBTOTAL_CENTS NUMBER(38,0) NOT NULL,
    PRODUCT_NAME VARCHAR(255),
    VARIANT_NAME VARCHAR(100),
    PRODUCT_IMAGE_URL VARCHAR(1000),
    ADDED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9),
    PRIMARY KEY (ITEM_ID),
    FOREIGN KEY (SESSION_ID) REFERENCES CART_OLTP.CART_SESSIONS(SESSION_ID),
    INDEX IDX_CART_ITEMS_SESSION(SESSION_ID)
);

CREATE OR REPLACE HYBRID TABLE ORDERS (
    ORDER_ID VARCHAR(36) NOT NULL,
    ORDER_NUMBER VARCHAR(20) NOT NULL,
    SESSION_ID VARCHAR(36),
    CUSTOMER_ID VARCHAR(36),
    STATUS VARCHAR(30) NOT NULL DEFAULT 'pending',
    SUBTOTAL_CENTS NUMBER(38,0) NOT NULL,
    TAX_CENTS NUMBER(38,0) NOT NULL,
    SHIPPING_CENTS NUMBER(38,0) NOT NULL,
    DISCOUNT_CENTS NUMBER(38,0) DEFAULT 0,
    TOTAL_CENTS NUMBER(38,0) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    SHIPPING_ADDRESS VARCHAR(2000),
    SHIPPING_METHOD VARCHAR(100),
    TRACKING_NUMBER VARCHAR(100),
    TRACKING_URL VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    CONFIRMED_AT TIMESTAMP_NTZ(9),
    SHIPPED_AT TIMESTAMP_NTZ(9),
    DELIVERED_AT TIMESTAMP_NTZ(9),
    CANCELLED_AT TIMESTAMP_NTZ(9),
    PRIMARY KEY (ORDER_ID),
    FOREIGN KEY (SESSION_ID) REFERENCES CART_OLTP.CART_SESSIONS(SESSION_ID),
    INDEX IDX_ORDER_CUSTOMER(CUSTOMER_ID),
    INDEX IDX_ORDER_NUMBER(ORDER_NUMBER),
    INDEX IDX_ORDER_STATUS(STATUS)
);

CREATE OR REPLACE HYBRID TABLE ORDER_ITEMS (
    ORDER_ITEM_ID VARCHAR(36) NOT NULL,
    ORDER_ID VARCHAR(36) NOT NULL,
    PRODUCT_ID VARCHAR(36) NOT NULL,
    VARIANT_ID VARCHAR(36),
    QUANTITY NUMBER(38,0) NOT NULL,
    UNIT_PRICE_CENTS NUMBER(38,0) NOT NULL,
    SUBTOTAL_CENTS NUMBER(38,0) NOT NULL,
    PRODUCT_NAME VARCHAR(255),
    VARIANT_NAME VARCHAR(100),
    PRODUCT_IMAGE_URL VARCHAR(1000),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    PRIMARY KEY (ORDER_ITEM_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES CART_OLTP.ORDERS(ORDER_ID),
    INDEX IDX_ORDER_ITEMS_ORDER(ORDER_ID)
);

CREATE OR REPLACE HYBRID TABLE PAYMENT_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(36) NOT NULL,
    SESSION_ID VARCHAR(36) NOT NULL,
    PAYMENT_METHOD_ID VARCHAR(36),
    AMOUNT_CENTS NUMBER(38,0) NOT NULL,
    CURRENCY VARCHAR(3) DEFAULT 'USD',
    STATUS VARCHAR(30) NOT NULL,
    PSP_NAME VARCHAR(50),
    PSP_TRANSACTION_ID VARCHAR(255),
    PSP_RESPONSE VARCHAR(4000),
    FAILURE_CODE VARCHAR(50),
    FAILURE_MESSAGE VARCHAR(500),
    CREATED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT TIMESTAMP_NTZ(9),
    PRIMARY KEY (TRANSACTION_ID),
    FOREIGN KEY (SESSION_ID) REFERENCES CART_OLTP.CART_SESSIONS(SESSION_ID),
    INDEX IDX_PAYMENT_SESSION(SESSION_ID)
);
