USE ROLE AGENT_COMMERCE_ROLE;
USE DATABASE AGENT_COMMERCE;
USE WAREHOUSE AGENT_COMMERCE_WH;

ALTER GIT REPOSITORY AGENT_COMMERCE.UTIL.AGENT_COMMERCE_GIT FETCH;

-- Copy stage files from git repo
COPY FILES INTO @PRODUCTS.PRODUCT_LABELS_STAGE FROM @UTIL.AGENT_COMMERCE_GIT/branches/main/data/product_labels/;
COPY FILES INTO @PRODUCTS.PRODUCT_MEDIA_STAGE/labels/ FROM @UTIL.AGENT_COMMERCE_GIT/branches/main/data/product_media/labels/;
COPY FILES INTO @CUSTOMERS.FACE_IMAGES_STAGE FROM @UTIL.AGENT_COMMERCE_GIT/branches/main/data/face_images/;
COPY FILES INTO @UTIL.EXECUTIVE_360_STAGE FROM @UTIL.AGENT_COMMERCE_GIT/branches/main/data/streamlit/;
COPY FILES INTO @UTIL.CSV_DATA_STAGE FROM @UTIL.AGENT_COMMERCE_GIT/branches/main/data/csv/;

ALTER STAGE PRODUCTS.PRODUCT_LABELS_STAGE REFRESH;
ALTER STAGE PRODUCTS.PRODUCT_MEDIA_STAGE REFRESH;
ALTER STAGE CUSTOMERS.FACE_IMAGES_STAGE REFRESH;

-- Load PRODUCTS schema tables
COPY INTO PRODUCTS.PRODUCTS
    FROM @UTIL.CSV_DATA_STAGE/PRODUCTS__PRODUCTS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PRODUCTS.PRODUCT_VARIANTS
    FROM @UTIL.CSV_DATA_STAGE/PRODUCTS__PRODUCT_VARIANTS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PRODUCTS.PRODUCT_MEDIA
    FROM @UTIL.CSV_DATA_STAGE/PRODUCTS__PRODUCT_MEDIA.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PRODUCTS.PRODUCT_LABELS
    FROM @UTIL.CSV_DATA_STAGE/PRODUCTS__PRODUCT_LABELS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PRODUCTS.PRODUCT_INGREDIENTS
    FROM @UTIL.CSV_DATA_STAGE/PRODUCTS__PRODUCT_INGREDIENTS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PRODUCTS.PRODUCT_WARNINGS
    FROM @UTIL.CSV_DATA_STAGE/PRODUCTS__PRODUCT_WARNINGS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PRODUCTS.PRICE_HISTORY
    FROM @UTIL.CSV_DATA_STAGE/PRODUCTS__PRICE_HISTORY.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO PRODUCTS.PROMOTIONS
    FROM @UTIL.CSV_DATA_STAGE/PRODUCTS__PROMOTIONS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Load SOCIAL schema tables
COPY INTO SOCIAL.PRODUCT_REVIEWS
    FROM @UTIL.CSV_DATA_STAGE/SOCIAL__PRODUCT_REVIEWS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO SOCIAL.SOCIAL_MENTIONS
    FROM @UTIL.CSV_DATA_STAGE/SOCIAL__SOCIAL_MENTIONS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO SOCIAL.INFLUENCER_MENTIONS
    FROM @UTIL.CSV_DATA_STAGE/SOCIAL__INFLUENCER_MENTIONS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Load INVENTORY schema tables
COPY INTO INVENTORY.LOCATIONS
    FROM @UTIL.CSV_DATA_STAGE/INVENTORY__LOCATIONS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO INVENTORY.STOCK_LEVELS
    FROM @UTIL.CSV_DATA_STAGE/INVENTORY__STOCK_LEVELS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO INVENTORY.INVENTORY_TRANSACTIONS
    FROM @UTIL.CSV_DATA_STAGE/INVENTORY__INVENTORY_TRANSACTIONS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Load CUSTOMERS schema tables
COPY INTO CUSTOMERS.CUSTOMERS
    FROM @UTIL.CSV_DATA_STAGE/CUSTOMERS__CUSTOMERS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CUSTOMERS.SKIN_ANALYSIS_HISTORY
    FROM @UTIL.CSV_DATA_STAGE/CUSTOMERS__SKIN_ANALYSIS_HISTORY.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Load CART_OLTP schema tables (hybrid)
COPY INTO CART_OLTP.CART_SESSIONS
    FROM @UTIL.CSV_DATA_STAGE/CART_OLTP__CART_SESSIONS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CART_OLTP.FULFILLMENT_OPTIONS
    FROM @UTIL.CSV_DATA_STAGE/CART_OLTP__FULFILLMENT_OPTIONS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CART_OLTP.PAYMENT_METHODS
    FROM @UTIL.CSV_DATA_STAGE/CART_OLTP__PAYMENT_METHODS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CART_OLTP.CART_ITEMS
    FROM @UTIL.CSV_DATA_STAGE/CART_OLTP__CART_ITEMS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CART_OLTP.ORDERS
    FROM @UTIL.CSV_DATA_STAGE/CART_OLTP__ORDERS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CART_OLTP.ORDER_ITEMS
    FROM @UTIL.CSV_DATA_STAGE/CART_OLTP__ORDER_ITEMS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

COPY INTO CART_OLTP.PAYMENT_TRANSACTIONS
    FROM @UTIL.CSV_DATA_STAGE/CART_OLTP__PAYMENT_TRANSACTIONS.csv
    FILE_FORMAT = (FORMAT_NAME = 'UTIL.CSV_FORMAT')
    MATCH_BY_COLUMN_NAME = CASE_INSENSITIVE;

-- Populate PRODUCT_LABEL_FILES from stage directory
INSERT INTO PRODUCTS.PRODUCT_LABEL_FILES
    SELECT RELATIVE_PATH FROM DIRECTORY(@PRODUCTS.PRODUCT_LABELS_STAGE);

-- Derive SKIN_TYPE_COMPATIBILITY for products
-- Step 1: Base skin type from finish
UPDATE PRODUCTS.PRODUCTS
SET SKIN_TYPE_COMPATIBILITY = 
    CASE 
        WHEN FINISH IN ('matte', 'powder') THEN ARRAY_CONSTRUCT('oily', 'combination')
        WHEN FINISH IN ('dewy', 'cream', 'satin') THEN ARRAY_CONSTRUCT('dry', 'combination')
        WHEN FINISH IN ('natural', 'semi-matte') THEN ARRAY_CONSTRUCT('normal', 'combination')
        ELSE ARRAY_CONSTRUCT('combination')
    END
WHERE SKIN_TYPE_COMPATIBILITY IS NULL OR ARRAY_SIZE(SKIN_TYPE_COMPATIBILITY) = 0;

-- Step 2: Add 'sensitive' for products with no allergens
UPDATE PRODUCTS.PRODUCTS p
SET SKIN_TYPE_COMPATIBILITY = ARRAY_APPEND(SKIN_TYPE_COMPATIBILITY, 'sensitive')
WHERE EXISTS (
    SELECT 1 FROM PRODUCTS.PRODUCT_INGREDIENTS pi 
    WHERE pi.PRODUCT_ID = p.PRODUCT_ID AND pi.IS_ALLERGEN = FALSE
    HAVING COUNT(*) > 0
)
AND NOT ARRAY_CONTAINS('sensitive'::VARIANT, SKIN_TYPE_COMPATIBILITY);
