USE ROLE AGENT_COMMERCE_ROLE;
USE DATABASE AGENT_COMMERCE;
USE WAREHOUSE AGENT_COMMERCE_WH;
USE SCHEMA PRODUCTS;

CREATE OR REPLACE DATA METRIC FUNCTION PRODUCTS.COST_EXCEEDS_PRICE(
    ARG_T TABLE(ARG_COST NUMBER(38,2), ARG_PRICE NUMBER(38,2))
)
RETURNS NUMBER(38,0)
LANGUAGE SQL
COMMENT = 'Counts rows where cost exceeds price'
AS
$$
  SELECT COUNT(*)
  FROM ARG_T
  WHERE ARG_COST > ARG_PRICE
$$;

ALTER TABLE PRODUCTS.PRODUCTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (UPDATED_AT);

ALTER TABLE PRODUCTS.PRODUCTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CURRENT_PRICE);

ALTER TABLE PRODUCTS.PRODUCTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE PRODUCTS.PRODUCTS
  ADD DATA METRIC FUNCTION PRODUCTS.COST_EXCEEDS_PRICE ON (COST, CURRENT_PRICE);

ALTER TABLE PRODUCTS.PRODUCTS
  SET DATA_METRIC_SCHEDULE = '*/5 * * * * UTC';
