USE ROLE AGENT_COMMERCE_ROLE;
USE DATABASE AGENT_COMMERCE;
USE WAREHOUSE AGENT_COMMERCE_WH;

-- Custom DMF: COST_EXCEEDS_PRICE is created in 05_create_udfs_procedures.sql

ALTER TABLE PRODUCTS.PRODUCTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.FRESHNESS ON (UPDATED_AT);

ALTER TABLE PRODUCTS.PRODUCTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.NULL_COUNT ON (CURRENT_PRICE);

ALTER TABLE PRODUCTS.PRODUCTS
  ADD DATA METRIC FUNCTION SNOWFLAKE.CORE.ROW_COUNT ON ();

ALTER TABLE PRODUCTS.PRODUCTS
  ADD DATA METRIC FUNCTION PRODUCTS.COST_EXCEEDS_PRICE ON (COST, CURRENT_PRICE);

ALTER TABLE PRODUCTS.PRODUCTS
  SET DATA_METRIC_SCHEDULE = '*/5 * * * * UTC';
