-- WARNING: This will permanently delete all data!

USE ROLE ACCOUNTADMIN;

DROP DATABASE IF EXISTS AGENT_COMMERCE;
DROP WAREHOUSE IF EXISTS AGENT_COMMERCE_WH;
DROP COMPUTE POOL IF EXISTS AGENT_COMMERCE_POOL;
DROP ROLE IF EXISTS AGENT_COMMERCE_ROLE;
DROP API INTEGRATION IF EXISTS AGENT_COMMERCE_GIT_INTEGRATION;
DROP NOTIFICATION INTEGRATION IF EXISTS EMAIL_INTEGRATION;
